### PR TITLE
Review

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**
Thanks for the module! :smiley:  I have some change suggestions.

There are no functional changes.

### CODE REVIEW

**Comment by KristjanESPERANTO** [comment]
@SalekurPolas did you noticed this PR? :slightly_smiling_face:

**Review by SalekurPolas — CHANGES_REQUESTED** [review]
Can you please add 
### async
### systeminformation
## Compatibility

Adding these will help beginners to understand how this module works.

**Comment by KristjanESPERANTO** [comment]
Okay, I just reentered the [Manual Installation](https://github.com/SalekurPolas/MMM-Pinfo/pull/9/commits/ffed33809a4c2b51d874e7bdce3b001a968aeb8f) section. Is that okay? :slightly_smiling_face:

**Comment by SalekurPolas** [comment]
Thanks for your work :)

**Pull request merged**
